/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerFilm;
import controller.ControllerJamTayang;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bella Febriany
 */
public class View_film extends javax.swing.JFrame {
 ControllerJamTayang controllerJamTayang = new ControllerJamTayang(this);
 ControllerFilm controllerFilm = new ControllerFilm(this);
    /**
     * Creates new form view_admin
     */
    
    public View_film() {
        initComponents();
        
        controllerFilm.readData(); 
        controllerJamTayang.readDataJam(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jJamTayang1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilm = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTittle = new javax.swing.JTextField();
        jGenre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jBtnSubmitFilm = new javax.swing.JButton();
        jBtnEditFilm = new javax.swing.JButton();
        jBtnDeleteFilm = new javax.swing.JButton();
        jBtnResetFilm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jJamTayang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBtnSubmitJam = new javax.swing.JButton();
        jBtnEditJam = new javax.swing.JButton();
        jBtnDeleteJam = new javax.swing.JButton();
        jBtnResetJam = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        iIdJam = new javax.swing.JTextField();
        jBtnMenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJamTayang = new javax.swing.JTable();
        jBtnLogout = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jJamTayang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJamTayang1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFilm);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Input Data Film");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Judul");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Genre");

        jTittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTittleActionPerformed(evt);
            }
        });

        jGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Price");

        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });

        jBtnSubmitFilm.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jBtnSubmitFilm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnSubmitFilm.setForeground(new java.awt.Color(51, 51, 51));
        jBtnSubmitFilm.setText("Submit");
        jBtnSubmitFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitFilmActionPerformed(evt);
            }
        });

        jBtnEditFilm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnEditFilm.setText("Update");
        jBtnEditFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditFilmActionPerformed(evt);
            }
        });

        jBtnDeleteFilm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnDeleteFilm.setText("Delete");
        jBtnDeleteFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteFilmActionPerformed(evt);
            }
        });

        jBtnResetFilm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnResetFilm.setText("Reset");
        jBtnResetFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetFilmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("ID");

        jId.setEditable(false);
        jId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTittle)
                            .addComponent(jGenre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnSubmitFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnEditFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnDeleteFilm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnResetFilm)
                                .addGap(0, 11, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(jId)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSubmitFilm)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditFilm)
                    .addComponent(jBtnDeleteFilm)
                    .addComponent(jBtnResetFilm))
                .addGap(27, 27, 27))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Input Jam Tayang");

        jJamTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJamTayangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Jam");

        jBtnSubmitJam.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jBtnSubmitJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnSubmitJam.setForeground(new java.awt.Color(51, 51, 51));
        jBtnSubmitJam.setText("Submit");
        jBtnSubmitJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitJamActionPerformed(evt);
            }
        });

        jBtnEditJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnEditJam.setText("Update");
        jBtnEditJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditJamActionPerformed(evt);
            }
        });

        jBtnDeleteJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnDeleteJam.setText("Delete");
        jBtnDeleteJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteJamActionPerformed(evt);
            }
        });

        jBtnResetJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnResetJam.setText("Reset");
        jBtnResetJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetJamActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ID");

        iIdJam.setEditable(false);
        iIdJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIdJamActionPerformed(evt);
            }
        });

        jBtnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnMenu.setText("Back to Menu");
        jBtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(66, 66, 66))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnMenu)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jJamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSubmitJam)
                            .addComponent(iIdJam, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnEditJam)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnDeleteJam)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnResetJam)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(iIdJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jJamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jBtnSubmitJam)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditJam)
                    .addComponent(jBtnDeleteJam)
                    .addComponent(jBtnResetJam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jBtnMenu)
                .addContainerGap())
        );

        jTableJamTayang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableJamTayang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJamTayangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableJamTayang);

        jBtnLogout.setBackground(java.awt.Color.lightGray);
        jBtnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnLogout.setForeground(new java.awt.Color(51, 51, 51));
        jBtnLogout.setText("Logout");
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Data Film :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Data Jam :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnLogout)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(29, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jBtnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTittleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTittleActionPerformed

    private void jGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenreActionPerformed

    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPriceActionPerformed

    private void jBtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenuActionPerformed
        // TODO add your handling code here:
        View_menuAdmin ma = new View_menuAdmin();
        ma.setVisible(true);
        ma.pack();
        ma.setLocationRelativeTo(null);
        ma.setDefaultCloseOperation(View_menuAdmin.EXIT_ON_CLOSE);
        dispose();  
    }//GEN-LAST:event_jBtnMenuActionPerformed

    private void jBtnEditFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditFilmActionPerformed
        // TODO add your handling code here:
        controllerFilm.updateData();
        controllerFilm.readData();
        controllerFilm.reset();
    }//GEN-LAST:event_jBtnEditFilmActionPerformed

    private void jJamTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJamTayangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJamTayangActionPerformed

    private void jBtnSubmitJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitJamActionPerformed
        // TODO add your handling code here:
        controllerJamTayang.insertData(); 
        controllerJamTayang.readDataJam(); 
        controllerJamTayang.reset();
    }//GEN-LAST:event_jBtnSubmitJamActionPerformed

    private void jBtnDeleteFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteFilmActionPerformed
        // TODO add your handling code here:
        controllerFilm.deleteData();
        controllerFilm.readData();
        controllerFilm.reset();
    }//GEN-LAST:event_jBtnDeleteFilmActionPerformed

    private void jBtnResetFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetFilmActionPerformed
        // TODO add your handling code here:
        controllerFilm.reset();
    }//GEN-LAST:event_jBtnResetFilmActionPerformed

    private void jBtnEditJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditJamActionPerformed
        // TODO add your handling code here:
        controllerJamTayang.updateData();
        controllerJamTayang.readDataJam();
        controllerJamTayang.reset();
    }//GEN-LAST:event_jBtnEditJamActionPerformed

    private void jBtnDeleteJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteJamActionPerformed
        // TODO add your handling code here:
        controllerJamTayang.deleteData();
        controllerJamTayang.readDataJam();
        controllerJamTayang.reset();
    }//GEN-LAST:event_jBtnDeleteJamActionPerformed

    private void jBtnResetJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetJamActionPerformed
        // TODO add your handling code here:
        controllerJamTayang.reset();
    }//GEN-LAST:event_jBtnResetJamActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        // TODO add your handling code here:
        View_login lg = new View_login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(View_login.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    private void jBtnSubmitFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitFilmActionPerformed
        // TODO add your handling code here:
         controllerFilm.insertData(); 
         controllerFilm.readData(); 
         controllerFilm.reset();
    }//GEN-LAST:event_jBtnSubmitFilmActionPerformed

    private void jIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdActionPerformed

    private void jTableFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFilmMouseClicked
        // TODO add your handling code here:
        int row = jTableFilm.getSelectedRow();
        controllerFilm.selectField(row);
    }//GEN-LAST:event_jTableFilmMouseClicked

    private void jJamTayang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJamTayang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJamTayang1ActionPerformed

    private void iIdJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIdJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIdJamActionPerformed

    private void jTableJamTayangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJamTayangMouseClicked
        // TODO add your handling code here:
        int row = jTableJamTayang.getSelectedRow();
        controllerJamTayang.selectField(row);
    }//GEN-LAST:event_jTableJamTayangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_film().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iIdJam;
    private javax.swing.JButton jBtnDeleteFilm;
    private javax.swing.JButton jBtnDeleteJam;
    private javax.swing.JButton jBtnEditFilm;
    private javax.swing.JButton jBtnEditJam;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnMenu;
    private javax.swing.JButton jBtnResetFilm;
    private javax.swing.JButton jBtnResetJam;
    private javax.swing.JButton jBtnSubmitFilm;
    private javax.swing.JButton jBtnSubmitJam;
    private javax.swing.JTextField jGenre;
    private javax.swing.JTextField jId;
    private javax.swing.JTextField jJamTayang;
    private javax.swing.JTextField jJamTayang1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPrice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFilm;
    private javax.swing.JTable jTableJamTayang;
    private javax.swing.JTextField jTittle;
    // End of variables declaration//GEN-END:variables

    
    public JTable getTableData() {
        return jTableFilm;
    }
    
     public JTable getTableDataa() {
        return jTableJamTayang;
    }
    
     public JTextField getId_film() {
         return jId;
     }
     
     public JTextField getTittle() {
         return jTittle;
     }

     public JTextField getGenre() {
        return jGenre;
    }

    public JTextField getPrice() {
        return jPrice;
    }

    public JTextField getTime() {
        return jJamTayang;
    }

    public JTextField getId_JamTayang() {
        return iIdJam;
    }
}
